import Head from "next/head";
import Footer from "./footer";
import Navbar from "./navbar";

const Layout = ({ children, title }) => {
  return (
    <>
      <Head>
        <title>{title ? title + "- Shoe Shop" : "Shoe Shop"}</title>
        <meta name="description" content="Generated by Code Wear" />
        <meta name="viewport" content="Ecommerce Website" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Navbar />

      {children}
      <Footer />
    </>
  );
};

export default Layout;
